# frozen_string_literal: true

source "https://rubygems.org"

ruby '3.3.0'
gem 'rails', '~> 7.1.0'

gem 'pg'
gem 'devise'

group :development, :test do
  gem 'dotenv-rails'
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'rubocop'
end
